services:
  - type: web
    name: quiniela-mundial-2026
    env: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
